# AzGovViz
# First things first: edit line 11 and line 56 
# https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting
# Also check https://www.azadvertizer.net to keep up with the pace on Azure Governance capabilities such as Azure Policies, Policy Initiatives, Policy Aliases and RBAC Roles

trigger: none

pr: none

variables:
  ManagementGroupId: <yourManagementGroupId>
  GitDir: /home/vsts/wiki
  OutputPath: /home/vsts/wiki/wikiRepo
  CsvDelimiter: ;
  Repository: wikiRepo
  AzGovVizScriptFolder: pwsh
  AzGovVizScript: AzGovViz.ps1

schedules:
- cron: "0 0,6,12,18 * * *"
  displayName: every 6h
  always: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: |
   write-host "Project: $(System.TeamProject)"
   write-host "Repository: $(Build.Repository.Name)"
   write-host "URL: $(System.TeamFoundationCollectionUri)"
   $PipelineInfo = "Pipeline: '$(Build.DefinitionName)' 'rev $(Build.BuildNumber)' (Project: $([uri]::EscapeDataString("$(System.TeamProject)")); Repository: $(Build.Repository.Name); Branch: $(Build.SourceBranchName) Commit: $(Build.SourceVersion))"
   write-host "PipelineInfo: $PipelineInfo" 
  displayName: 'PowerShell Script - testing'
  env:
    workingdirectory: $(Agent.BuildDirectory)

- powershell: |
   mkdir $(GitDir)
   cd $(GitDir)
   $TeamProjectUriFormat = [uri]::EscapeDataString("$(System.TeamProject)")
   git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" $(System.TeamFoundationCollectionUri)$TeamProjectUriFormat/_git/$(Repository)
   write-host "install Az.ResourceGraph"
   Install-Module -Name Az.ResourceGraph -Force
  displayName: 'PowerShell Script - Git clone'
  env:
    workingdirectory: $(Agent.BuildDirectory)

- task: AzurePowerShell@4
  displayName: 'Azure PowerShell script: FilePath'
  continueOnError: true
  inputs:
    azureSubscription: '<yourServiceConnection>'
    ScriptPath: '$(System.DefaultWorkingDirectory)/$(AzGovVizScriptFolder)/$(AzGovVizScript)'
    ScriptArguments: '-ManagementGroupId $(ManagementGroupId) -OutputPath $(OutputPath) -CsvDelimiter "$(CsvDelimiter)" -AzureDevOpsWikiAsCode'
    preferredAzurePowerShellVersion: 3.1.0
    errorActionPreference: continue

- powershell: |
   write-host $(Agent.Name)
   cd $(OutputPath)
   $executionDateTimeInternationalReadable = get-date -format "dd-MMM-yyyy HH:mm:ss"
   $currentTimeZone = (Get-TimeZone).Id
   git config --global user.email "pipeline@ado.com"
   $PipelineInfo = "Pipeline: '$(Build.DefinitionName)' 'rev $(Build.BuildNumber)' (Project: $([uri]::EscapeDataString("$(System.TeamProject)")); Repository: $(Build.Repository.Name); Branch: $(Build.SourceBranchName) Commit: $(Build.SourceVersion))"
   git config --global user.name "$PipelineInfo"
   git pull
   git add --all
   git commit -m "wiki $executionDateTimeInternationalReadable ($currentTimeZone)"
   git push
  displayName: 'PowerShell Script - Git push'
