# AzGovViz v6_major_20220116_2
name: AzGovViz_OIDC

env:
  outputpath: wiki
  ManagementGroupId: <managementGroupId>

on:
  schedule:
    - cron:  '45 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#requirement OIDC
permissions:
  id-token: write
  contents: write

jobs:
  AzGovViz:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Connect Azure OIDC
        uses: azure/login@v1
        with:
          client-id: ${{secrets.CLIENT_ID}}
          tenant-id: ${{secrets.TENANT_ID}}
          subscription-id: ${{secrets.SUBSCRIPTION_ID}} 
          enable-AzPSSession: true
       
      - name: Check prerequisites
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pwsh\prerequisites.ps1
          azPSVersion: "latest"

      - name: Run AzGovViz
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pwsh\AzGovVizParallel.ps1 -ManagementGroupId ${env:ManagementGroupId} -SubscriptionId4AzContext ${{secrets.SUBSCRIPTION_ID}} -outputpath ${env:outputpath}
          azPSVersion: "latest"
      
      - name: Push AzGovViz output to repository
        run: |        
          git config --global user.email "AzGovVizGHActions@ghActions.com"
          git config --global user.name "azgvz"
          git config pull.rebase false
          git add --all
          git commit -m "$GITHUB_WORKFLOW $GITHUB_JOB"
          git push